"""Public workflow API for NegAccel Python tooling."""

from .cli import build_parser, main
from .common import (
    DEFAULT_OUTPUTS,
    REPO_ROOT,
    WorkflowError,
    apply_cli_overrides,
    apply_override_pairs,
    ensure_case_metadata,
    load_json,
    merge_objects,
    parse_path,
    parse_value,
    require_number,
    require_object,
    require_string,
    resolve_default_case_output,
    sanitize_case_tag,
    set_path,
    write_json,
)
from .geometry_files import (
    TEMPLATES_DIR,
    load_geometry_file,
    load_geometry_reference,
    resolve_geometry_file_path,
    serialize_geometry_file_path,
    write_geometry_file,
)
from .domains.geometry_validation import derive_diagnostic_planes
from .post_processing import (
    aggregate_case_diagnostics,
    parse_diagnostic_summary_txt,
    parse_grid_power_breakdown_txt,
    parse_grid_power_summary_txt,
    synthesize_scan_results,
    write_case_diagnostics_aggregation,
    write_scan_synthesis,
)
from .runtime import authored_to_runtime_case, materialize_authored_case, materialize_case
from .scan import build_case_tag, expand_scan, run_scan

__all__ = [
    "DEFAULT_OUTPUTS",
    "REPO_ROOT",
    "WorkflowError",
    "apply_cli_overrides",
    "apply_override_pairs",
    "aggregate_case_diagnostics",
    "authored_to_runtime_case",
    "build_case_tag",
    "build_parser",
    "TEMPLATES_DIR",
    "ensure_case_metadata",
    "expand_scan",
    "derive_diagnostic_planes",
    "load_json",
    "load_geometry_file",
    "load_geometry_reference",
    "main",
    "materialize_authored_case",
    "materialize_case",
    "merge_objects",
    "parse_diagnostic_summary_txt",
    "parse_grid_power_breakdown_txt",
    "parse_grid_power_summary_txt",
    "parse_path",
    "parse_value",
    "require_number",
    "require_object",
    "require_string",
    "resolve_default_case_output",
    "resolve_geometry_file_path",
    "run_scan",
    "sanitize_case_tag",
    "serialize_geometry_file_path",
    "set_path",
    "synthesize_scan_results",
    "write_case_diagnostics_aggregation",
    "write_geometry_file",
    "write_json",
    "write_scan_synthesis",
]
